baseURL: https://danyel-website.netlify.app/
languageCode: en-us
title: Website for DSB
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      \#A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      \#AND RELEASED UNDER THE CREATIVE COMMONS.
    title: My name is Danyel Desa. I am passionate about data science and coding
  blog: {}
  contact:
    address:
      - city: London, NW8 8UN
        country: United Kingdom
        street: North Bank
        title: Flat 36, Regent Court
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ddesa.mba2024@london.edu
        title: Email
    enable: yes
    phone:
      - phone: 07557 680 144
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Danyel Desa
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        \#text: 'Design: '
        \#url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com/danyeldesa
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/danyel_desa
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/danyeldesa
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/danyeldesa
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - \#name: Generic Blog
        \#url: blogs/ipsum
      - \#name: Elements
        \#url: elements.html
    menu: Menu
    \#subtitle: By HTML5 Up
    \#title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic06.jpg
        subtitle: Project on data science basics
        title: Intro to Data Science
        url: https://github.com/danyeldesa/dsb23-danyel/tree/main/session01_lecture1
      - image: plots.png
        subtitle: Exploration of plots
        title: Plotting and visualizing
        url: https://github.com/danyeldesa/dsb23-danyel/tree/main/session03_lecture2
      - image: clustering.jpg
        subtitle: Further analysis of data processing and visualization
        title: Advanced Data Science Techniques
        url: https://github.com/danyeldesa/dsb23-danyel/tree/main/session05_lecture3
      - image: machine_learning.jpg
        subtitle: Exploration of machine learning techniques
        title: Machine Learning
        url: https://github.com/danyeldesa/dsb23-danyel/tree/main/session07_lecture4
      - image: cv.png
        subtitle: My curriculum vitae
        title: Resume
        url: https://github.com/danyeldesa/CV
      - image: pic02.jpg
        subtitle: Link to a blog piece on renewable energy that I authored
        title: Blog
        url: https://www.renewableenergyworld.com/hydrogen/big-oils-interest-in-hydrogen-boon-or-bane/#gref
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "I am currently a first-year MBA student at London Business School.      \r\n    I aspire to break in to the technology industry upon my graduation and I am actively working on building these skills. \r\n    I graduated
      with a bachelor's and master's degree in electrical engineering and spent 4 years working in finance. Here you can find links to a few data science projects that I have undertaken, along with my CV, and a link to a blog that I wrote about renewable energy."
    title: About Me
    url: blogs

markup: 
  goldmark: 
    renderer: 
      unsafe: true
